create table if not exists public."Products" (
    id bigint generated by default as identity primary key,
    canonical_name text not null,
    grade text,
    scale text,
    msrp numeric check (msrp >= 0),
    msrp_currency text not null default 'JPY',
    original_release_date date,
    last_reproduction_date date,
    source_url text,
    metadata_checked_at timestamptz
);

alter table public."Listings"
add column if not exists product_id bigint references public."Products"(id);

create index if not exists listings_product_id_idx
on public."Listings"(product_id);

create table if not exists public."AiPricingSuggestions" (
    id uuid primary key default gen_random_uuid(),
    created_at timestamptz not null default now(),
    suggested_price numeric check (suggested_price >= 0),
    suggested_carousell_price numeric check (suggested_carousell_price >= 0),
    tag_names text[] not null default '{}',
    comparable_listing_ids bigint[] not null default '{}',
    product_id bigint references public."Products"(id) on delete set null,
    accepted_listing_id bigint references public."Listings"(id) on delete set null,
    accepted_price numeric check (accepted_price >= 0),
    accepted_carousell_price numeric check (accepted_carousell_price >= 0)
);

alter table public."Products" enable row level security;
alter table public."AiPricingSuggestions" enable row level security;

create policy "Products are publicly readable"
on public."Products"
for select
using (true);

create policy "Admins can manage products"
on public."Products"
for all
to authenticated
using (
    exists (
        select 1
        from public."Users"
        where auth_user_id = auth.uid()
          and is_admin = true
    )
)
with check (
    exists (
        select 1
        from public."Users"
        where auth_user_id = auth.uid()
          and is_admin = true
    )
);

create policy "Admins can manage AI pricing suggestions"
on public."AiPricingSuggestions"
for all
to authenticated
using (
    exists (
        select 1
        from public."Users"
        where auth_user_id = auth.uid()
          and is_admin = true
    )
)
with check (
    exists (
        select 1
        from public."Users"
        where auth_user_id = auth.uid()
          and is_admin = true
    )
);
